"""add musicbrainz fields, membership dates, discography exclusions

Revision ID: 88abb6a0dcc8
Revises: d22846df68d9
Create Date: 2026-06-08 23:12:13.405240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88abb6a0dcc8'
down_revision = 'd22846df68d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musicbrainz_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('discography_country', sa.String(length=2), nullable=True))

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('begin_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=True))

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musicbrainz_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('mb_cover_image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_column('mb_cover_image_url')
        batch_op.drop_column('musicbrainz_id')

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('is_current')
        batch_op.drop_column('end_date')
        batch_op.drop_column('begin_date')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('discography_country')
        batch_op.drop_column('musicbrainz_id')

    # ### end Alembic commands ###
