"""add hidden to artists

Revision ID: 94ace34e0eee
Revises: cc4f8e9747e7
Create Date: 2026-03-21 11:13:56.974855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ace34e0eee'
down_revision = 'cc4f8e9747e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
