"""add hidden to releases

Revision ID: cc4f8e9747e7
Revises: f0824b06f081
Create Date: 2026-03-15 12:17:54.658550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4f8e9747e7'
down_revision = 'f0824b06f081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
