"""add display_name to artists, format_override to releases

Revision ID: d97bd8481458
Revises: 1ec934156363
Create Date: 2026-05-30 00:00:31.292245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97bd8481458'
down_revision = '1ec934156363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=200), nullable=True))

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format_override', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_column('format_override')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
