"""add short_title to releases

Revision ID: f0824b06f081
Revises: ce6872672386
Create Date: 2026-03-15 11:03:37.891702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0824b06f081'
down_revision = 'ce6872672386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_title', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_column('short_title')

    # ### end Alembic commands ###
